Auto forwarder implementation
webhook-buddy/webhook-buddy-client pull request #6
Opened 2021-03-10 21:06 UTC by esinarta

- Re-activated AutoForwarder and Docker UI components 
- Added default value for endpoint picker rather than having one selected automatically
- Implemented auto-forwarding inside AutoForwarder component
- Created new AutoForwarderWebhookCreated type for GraphQL subscription

2021-03-12 20:43 UTC, johnnyoshika requested changes

2021-03-12 20:43 UTC, johnnyoshika commented on src/routes/Viewport/AutoForwarder/index.tsx
> +  const { forwardWebhook } = useForwarder(endpointId);
When endpointId is empty (i.e. ''), `useForwardUrls(endpointId)` is causing a GraphQL error, as it tries to fetch forward URLs for an endpoint that's empty.  Here is the request that's being sent:

![image](https://user-images.githubusercontent.com/504505/110995383-25741c00-832f-11eb-8f46-15b425e2284f.png)

This results in this response from our GraphQL server:

![image](https://user-images.githubusercontent.com/504505/110995616-826fd200-832f-11eb-879e-0aefa309cb44.png)

Also, every time I change the endpoint from the dropdown, the same request is being sent with an empty endpointId. You can test this by putting a breakpoint here, as that code will be called on every GraphQL error: https://github.com/webhook-buddy/webhook-buddy-client/blob/master/src/index.tsx#L72

You can also see this error being printed to the console:
![image](https://user-images.githubusercontent.com/504505/110995990-19d52500-8330-11eb-8a12-ffc9569f32ee.png)

To fix this, I suggest you extract this into a separate component, and only load it when an appropriate endpoint is selected:
```
        <label>Auto-forward to</label>
        <Autosuggest
          type="url"
          placeholder="Forward to URL (e.g. http://localhost:8000/send-webhook-here)"
          userInput={url}
          setUserInput={setUrl}
          suggestions={forwardUrls}
          position={AutosuggestPositionEnum.Up}
          disabled={running}
        />
      </div>
```

You may also want to extract the endpoint select list to a separate component as well to make it consistent.

2021-03-12 23:08 UTC, johnnyoshika commented
@esinarta Before you make further changes, can you rebase on top of this main repo's master branch? It looks like your branch hasn't picked up the latest changes. If you haven't set up this repo as a remote repo, you can do something like this:

```
git remote add source https://github.com/webhook-buddy/webhook-buddy-client.git
git fetch source
git rebase source/master
git push -f
```

2021-03-12 23:13 UTC, esinarta commented
> @esinarta Before you make further changes, can you rebase on top of this main repo's master branch? It looks like your branch hasn't picked up the latest changes. If you haven't set up this repo as a remote repo, you can do something like this:
> 
> ```
> git remote add source https://github.com/webhook-buddy/webhook-buddy-client.git
> git fetch source
> git rebase source/master
> git push -f
> ```

@johnnyoshika Okay, I just followed these steps to rebase.

2021-03-25 17:01 UTC, BuzzBumble commented
@johnnyoshika  

> Also, every time I change the endpoint from the dropdown, the same request is being sent with an empty endpointId. 

We couldn't seem to recreate this bug (maybe we fixed it inadvertently?)

> When endpointId is empty (i.e. ''), useForwardUrls(endpointId) is causing a GraphQL error, as it tries to fetch forward URLs for an endpoint that's empty.

This is now fixed, since the AutoSuggest is now in its own conditionally-rendered component and the useForwardURLs hook is being used within that component.

The last concern is that when a webhook is auto-forwarded, the profiler is noticing 10+ re-renders of the AutoForwarder's child components (namely `AutoForwardSuggest`). Still looking into this.

2021-03-26 06:15 UTC, johnnyoshika commented
> The last concern is that when a webhook is auto-forwarded, the profiler is noticing 10+ re-renders of the AutoForwarder's child components (namely `AutoForwardSuggest`). Still looking into this.

Thanks @BuzzBumble. Would you like me to wait until the rendering issues are resolved or proceed with the review? We can also review the render problem together tomorrow.

2021-04-02 16:05 UTC, johnnyoshika commented
A couple of issues:

* I'm still seeing the `FORBIDDEN error` when I switch endpoints due to the empty `endpointId` being passed to `forwardUrls` query:

![image](https://user-images.githubusercontent.com/504505/113432237-dbacad80-9391-11eb-8740-017b5cf5f042.png)

* I think you can delete everything inside `src/hooks/types`. Our types generation tool doesn't delete existing types. Try deleting that folder and then re-run the type generation. If the deleted ones don't get re-recreated, they were safe to delete.

2021-04-02 16:08 UTC, johnnyoshika requested changes

2021-04-02 16:08 UTC, johnnyoshika commented on src/routes/Viewport/AutoForwarder/index.tsx
> +import { WebhookCreated } from 'hooks/types/WebhookCreated';
This is referencing types inside `hooks/types` instead of `schema/types`

2021-04-02 18:51 UTC, esinarta commented
I deleted the hooks/types folder and re-ran types-generate and none of the types were re-created. I also changed the WebhookCreated import to reference schema/types.

2021-04-05 05:57 UTC, johnnyoshika approved these changes

2021-04-05 05:57 UTC, merged

2021-04-05 06:25 UTC, johnnyoshika commented
Thanks for the PR. Well done, guys!